repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # v1.38.0
    hooks:
      - id: yamllint

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: c5755e272a13da06be38d74052658af46c1ee447 # v0.9.35
    hooks:
      - id: pymarkdown

  - repo: https://github.com/gitleaks/gitleaks
    rev: 6eaad039603a4de39fddd1cf5f727391efe9974e # v8.30.0
    hooks:
      - id: gitleaks
